# Generated by Django 3.1.1 on 2021-12-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20211206_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='members_limite',
            new_name='members_limit',
        ),
    ]
